apiVersion: apps/v1
kind: Deployment
metadata:
  name: baran-guestbook-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baran-guestbook-backend
  template:
    metadata:
      labels:
        app: baran-guestbook-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/sadecebar/baran-guestbook-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: baran-postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: baran-postgres-secret
                  key: POSTGRESQL_DATABASE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: baran-postgres-secret
                  key: POSTGRESQL_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: baran-postgres-secret
                  key: POSTGRESQL_PASSWORD
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: baran-backend
spec:
  selector:
    app: baran-guestbook-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
