apiVersion: v1
kind: Secret
metadata:
  name: baran-postgres-secret
type: Opaque
stringData:
  POSTGRESQL_DATABASE: guestbook
  POSTGRESQL_USERNAME: guest
  POSTGRESQL_PASSWORD: ocp123
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: baran-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: lvms-vg1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baran-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baran-postgres
  template:
    metadata:
      labels:
        app: baran-postgres
    spec:
      containers:
        - name: postgres
          image: docker.io/bitnamilegacy/postgresql:16.6.0-debian-12-r2
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: baran-postgres-secret
                  key: POSTGRESQL_DATABASE
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: baran-postgres-secret
                  key: POSTGRESQL_USERNAME
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: baran-postgres-secret
                  key: POSTGRESQL_PASSWORD
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: postgres-data
              mountPath: /bitnami/postgresql
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: baran-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: baran-postgres
spec:
  selector:
    app: baran-postgres
  ports:
    - name: tcp-5432
      port: 5432
      targetPort: 5432
