name: Build and Push Guestbook Containers

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push backend
        run: |
          docker build \
            -t ghcr.io/sadecebar/baran-guestbook-backend:latest \
            -f guestbook-backend/Dockerfile \
            .
          docker push ghcr.io/sadecebar/baran-guestbook-backend:latest

      - name: Build and push frontend
        run: |
          docker build \
            -t ghcr.io/sadecebar/baran-guestbook-frontend:latest \
            -f guestbook-frontend/Dockerfile \
            .
          docker push ghcr.io/sadecebar/baran-guestbook-frontend:latest
